datawarehouse:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "123456"
      dbname: staging
      schema: staging

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "123456"
      dbname: staging
      schema: staging

  target: dev
